package weibo.actions;
import com.opensymphony.xwork2.ActionSupport;

// Generated 2018-3-29 20:15:34 by Hibernate Tools 4.3.1



/**
 * Focus generated by hbm2java
 */
public class Focus extends ActionSupport implements java.io.Serializable {

    private int symbol;
    private String id;
    private String id1;

    public Focus() {
    }

    public Focus(int symbol, String id, String id1) {
       this.symbol = symbol;
       this.id = id;
       this.id1 = id1;
    }
   
    
    public int getSymbol() {
        return this.symbol;
    }
    
    public void setSymbol(int symbol) {
        this.symbol = symbol;
    }
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getId1() {
        return this.id1;
    }
    
    public void setId1(String id1) {
        this.id1 = id1;
    }




}


