package myHibernate;
// Generated 2018-3-29 20:15:34 by Hibernate Tools 4.3.1



/**
 * Opinion generated by hbm2java
 */
public class Opinion  implements java.io.Serializable {


     private int symbol;
     private int msgId;
     
     private String id;
     private String comment;
     private int praise;

    public Opinion() {
    }

    public Opinion(int symbol, int msgId, String id, String comment, int praise) {
       this.symbol = symbol;
       this.msgId = msgId;
       this.id = id;
       this.comment = comment;
       this.praise = praise;
    }
   
    public int getSymbol() {
        return this.symbol;
    }
    
    public void setSymbol(int symbol) {
        this.symbol = symbol;
    }
    public int getMsgId() {
        return this.msgId;
    }
    
    public void setMsgId(int msgId) {
        this.msgId = msgId;
    }
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public int getPraise() {
        return this.praise;
    }
    
    public void setPraise(int praise) {
        this.praise = praise;
    }




}


