package myHibernate;
// Generated 2018-3-29 20:15:34 by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String id;
     private String code;
     private String nickname;
     private String icon;
     private String type;

    public User() {
    }

	
    public User(String id, String code, String nickname) {
        this.id = id;
        this.code = code;
        this.nickname = nickname;
    }
    public User(String id, String code, String nickname, String icon,String type) {
       this.id = id;
       this.code = code;
       this.nickname = nickname;
       this.icon = icon;
       this.setType(type);
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }


	public String getType() {
		return type;
	}


	public void setType(String type) {
		this.type = type;
	}

    
}


