package myHibernate;
// Generated 2018-3-29 20:15:34 by Hibernate Tools 4.3.1



/**
 * Weibo generated by hbm2java
 */
public class Weibo  implements java.io.Serializable {


     private int msgId;
     private String id;
     private String imagePath;
     private String text;

    public Weibo() {
    }

    public Weibo(int msgId, String id, String imagePath, String text) {
       this.msgId = msgId;
       this.id = id;
       this.imagePath = imagePath;
       this.text = text;
    }
   
    public int getMsgId() {
        return this.msgId;
    }
    
    public void setMsgId(int msgId) {
        this.msgId = msgId;
    }
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getImagePath() {
        return this.imagePath;
    }
    
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


